// Cache hashes for the media this offshoot actually ships; originals stay intact.
'use strict';
const fs=require('node:fs'), path=require('node:path'), crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'tools/ship_manifest.json'),'utf8'));
const voice={},sfx={};
function scan(rel) {
  const full=path.join(root,rel);
  if(!fs.existsSync(full))throw new Error('Missing media '+rel);
  if(fs.statSync(full).isDirectory())return fs.readdirSync(full).sort().forEach(n=>scan(rel+'/'+n));
  if(!rel.endsWith('.mp3'))return;
  const hash=crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex').slice(0,12);
  if(rel.startsWith('audio/vo/'))voice[rel]=hash;
  if(rel.startsWith('audio/sfx/'))sfx[path.basename(rel,'.mp3')]=hash;
}
for(const rel of [...manifest.files,...manifest.dirs]) if(/^audio\/(vo|sfx)(\/|$)/.test(rel))scan(rel);
const code='// Generated by tools/build_media_hashes.js from shipped audio files.\n'
  +'ADV.DATA.VOICE_HASHES='+JSON.stringify(voice)+';\n'
  +'ADV.DATA.SFX_HASHES='+JSON.stringify(sfx)+';\n';
fs.writeFileSync(path.join(root,'js/expedition/media_hashes.js'),code);
console.log('Media cache: '+Object.keys(voice).length+' voices, '+Object.keys(sfx).length+' effects, '+Buffer.byteLength(code)+' bytes.');

