// Adventurer: Expeditions — write docs/LEVELS.md from the game's own data.
//
// Hiro, 2026-09-21: "I haven't been able to assist with making levels and quest
// because I can't see what levels exist easily." So this reads campaign.js and
// data.js and prints every quest exactly as the game has it — locations, sky,
// music, each wave's enemies, what is open and what is not, and which art the
// package actually carries. Generated, never hand-edited, so it cannot drift.
//
//   node tools/levels_doc.js          write docs/LEVELS.md
//   node tools/levels_doc.js --check  fail if the file is out of date
'use strict';
const path = require('node:path'), fs = require('node:fs'), vm = require('node:vm');
const ROOT = path.join(__dirname, '..');
const A = require('../test/harness.js').load();
for (const f of ['js/expedition/data.js', 'js/expedition/shim.js', 'js/expedition/encounter.js', 'js/expedition/campaign.js']) {
  vm.runInThisContext(fs.readFileSync(path.join(ROOT, f), 'utf8'), { filename: f });
}
const X = A.Expedition, Camp = X.Campaign;
const ship = new Set(require('./size_check.js').shipList().files);
const ALIAS = { bandit_road: 'road', deep_wood: 'forest', shallows: 'coast' };
const plateFile = p => 'assets/anime/v2/runtime/' + (ALIAS[p] || p) + '.webp';
const shipped = new Set((X.shipped && X.shipped.actors) || []);

const artOf = key => {
  const d = X.enemies[key] || {};
  if (d.human || d.kind === 'human') return { actor: 'human', ok: false, note: 'composed from the old part sheets — not a reworked set' };
  const actor = d.artActor || (d.kind === 'boss' ? 'alpha' : d.kind);
  return { actor, ok: shipped.has(actor), note: shipped.has(actor) ? '' : 'NOT in the build' };
};
const name = key => (X.enemies[key] && X.enemies[key].name) || key.replace(/_/g, ' ');

const L = [];
const order = (X.slice.openQuests || []).slice();
const open = new Set(order);
// Play order first, then anything retired from the rotation.
const inOrder = order.map(id => Camp.quest(id)).filter(Boolean)
  .concat(X.quests.filter(q => !open.has(q.id)));
const stepOf = id => { const i = order.indexOf(id); return i < 0 ? 'retired' : 'level ' + (i + 1); };
L.push('# Adventurer: Expeditions — the levels, as the game has them');
L.push('');
L.push('*Generated by `node tools/levels_doc.js` from `campaign.js` and `data.js`. Do not edit by hand —');
L.push('change the game and re-run it. Written ' + new Date().toISOString().slice(0, 10) + '.*');
L.push('');
L.push('**How a quest is built:** three waves, each on a background plate; one travel panorama shown');
L.push('before, between and after the fights; one music track for the whole quest; one sky and one');
L.push('time of day. Change any of those and you have a different level.');
L.push('');
L.push('**The run plays them in this order:** ' + order.map((id, i) => (i + 1) + '. ' + Camp.quest(id).title).join('  ·  ') + '.');
L.push('');
L.push('| # | Quest | Backgrounds (wave 1 / 2 / 3) | Travel | Sky | Time | Music |');
L.push('|---|---|---|---|---|---|---|');
for (const q of inOrder) {
  const plates = q.plates.map(p => (ALIAS[p] || p) + (ship.has(plateFile(p)) ? '' : ' ⚠')).join(' / ');
  L.push('| ' + stepOf(q.id) + ' | **' + q.title + '** `' + q.id + '`' + (open.has(q.id) ? '' : ' — *not in the rotation; dev preview only*') + ' | ' +
    plates + ' | ' + q.travel + ' | ' + q.weather + ' | ' + q.phase + ' | ' + q.music + ' |');
}
L.push('');
L.push('⚠ = that plate is not in the packaged build, so the quest cannot open until it is added.');
L.push('');
L.push('## What you fight, wave by wave');
L.push('');
for (const q of inOrder) {
  L.push('### ' + stepOf(q.id) + ' — ' + q.title + '  `' + q.id + '`');
  L.push('');
  L.push('*' + q.weather + ' ' + q.phase + ', travelling through the ' + q.travel + ', to ' + q.music + '.*');
  L.push('');
  L.push('| Wave | Background | Enemies | Gold | Art |');
  L.push('|---|---|---|---|---|');
  Camp.questEncounters(q.id).forEach((e, i) => {
    const arts = (e.enemies || []).map(artOf);
    const bad = arts.filter(a => !a.ok);
    L.push('| ' + (i + 1) + (e.boss ? ' **boss**' : '') + ' | ' + (ALIAS[e.bg] || e.bg) + ' | ' +
      (e.enemies || []).map(name).join(', ') + ' | ' + (e.gold || 0) + ' | ' +
      (bad.length ? '⚠ ' + [...new Set(bad.map(b => b.note))].join('; ') : 'all reworked') + ' |');
  });
  L.push('');
}
L.push('## The creatures you can build a level from');
L.push('');
L.push('Only these have reworked art. Anything else in the game is plate art and should not be');
L.push('used in a quest until its set is painted.');
L.push('');
L.push('| Creature | Clips / frames | Hiro finishing moves | In the build |');
L.push('|---|---|---|---|');
for (const id of ['wolf', 'plant', 'alpha', 'boar']) {
  let clips = 0, frames = 0, fin = 0;
  try {
    const at = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/expedition/' + id + '/' + id + '.json'), 'utf8'));
    const cs = at.clips || {};
    clips = Object.keys(cs).length;
    frames = Object.values(cs).reduce((n, c) => n + (c.frames || []).length, 0);
    fin = Object.keys(cs).filter(c => /paired/.test(c)).length;
  } catch (e) {}
  try {
    const hiro = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/expedition/hiro/hiro.json'), 'utf8'));
    const pre = id === 'wolf' ? /^(wolf-|bite-)/ : id === 'plant' ? /^plant-/ : null;
    if (pre) fin += Object.keys(hiro.clips || {}).filter(c => pre.test(c) && /paired/.test(c)).length;
  } catch (e) {}
  L.push('| ' + id + ' | ' + clips + ' / ' + frames + ' | ' + (fin || '**none**') + ' | ' + (shipped.has(id) ? 'yes' : 'no') + ' |');
}
L.push('');
L.push('## The locations you can choose from');
L.push('');
L.push('The website game carries far more art than this build uses. Adding one is a line in');
L.push('`tools/ship_manifest.json` plus a sync; each plate is roughly 0.26–0.48 MB.');
L.push('');
const dir = p => { try { return fs.readdirSync(path.join(ROOT, '..', 'adventurer', p)).filter(f => f.endsWith('.webp')); } catch (e) { return []; } };
const skip = /heads_|wardrobe|headgear|creatures_|forms_|props_|children|hiro_cyber/;
const plates = dir('assets/anime/v2/runtime').filter(f => !skip.test(f)).map(f => f.replace('.webp', ''));
const panos = dir('assets/anime/travel/v1/runtime').map(f => f.replace('.webp', ''));
const mark = (list, inBuild) => list.map(n => inBuild(n) ? '**' + n + '**' : n).join(', ');
L.push('**Backgrounds (' + plates.length + ')** — bold are already in the build: ');
L.push(mark(plates, n => ship.has('assets/anime/v2/runtime/' + n + '.webp')));
L.push('');
L.push('**Travel panoramas (' + panos.length + ')** — bold are already in the build: ');
L.push(mark(panos, n => ship.has('assets/anime/travel/v1/runtime/' + n + '.webp')));
L.push('');
L.push('**Skies:** ' + Object.keys(X.weatherKinds).join(', ') + '.  **Times:** day, evening, night.');
L.push('');
L.push('## To change a level, tell me');
L.push('');
L.push('the quest, and any of: its three backgrounds, its travel panorama, its sky and time, its');
L.push('music, and the enemies in each wave. Everything above is the current answer to each of those.');
L.push('');

const out = L.join('\n') + '\n';
const dest = path.join(ROOT, 'docs', 'LEVELS.md');
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
  if (cur !== out) { console.error('docs/LEVELS.md is out of date — run: node tools/levels_doc.js'); process.exit(1); }
  console.log('levels_doc: docs/LEVELS.md is current');
} else {
  fs.writeFileSync(dest, out);
  console.log('wrote docs/LEVELS.md (' + X.quests.length + ' quests)');
}
